import {
  Dashboard,
  AccountBox,
  Person,
  SentimentSatisfiedAlt,
  // Block,
  EventAvailable,
  Storefront,
  EmojiPeople,
  // Today,
  // Shop,
  // SettingsApplications,
  ListAlt,
  ViewList,
  PeopleAlt,
} from "@material-ui/icons";
export const SidebarData = [
  {
    title: "Dashboard",
    class: "slidebar-nav-item",
    url: "/dashboard",
    urlClass: "slidebar-nav-link",
    icon: Dashboard,
    iconClass: "slide-icon",
  },
  {
    title: "Personal",
    class: "slidebar-nav-item",
    url: "/dashboard/personal",
    url2: "/dashboard/personal/create",
    urlClass: "slidebar-nav-link",
    icon: Person,
    iconClass: "slide-icon",
  },
  {
    title: "Odontologos",
    class: "slidebar-nav-item",
    url: "/dashboard/odontologos",
    urlClass: "slidebar-nav-link",
    icon: PeopleAlt,
    iconClass: "slide-icon",
  },
  {
    title: "Clientes",
    class: "slidebar-nav-item",
    url: "/dashboard/clientes",
    urlClass: "slidebar-nav-link",
    icon: EmojiPeople,
    iconClass: "slide-icon",
  },
  {
    title: "Pacientes",
    class: "slidebar-nav-item",
    url: "/dashboard/pacientes",
    urlClass: "slidebar-nav-link",
    icon: SentimentSatisfiedAlt,
    iconClass: "slide-icon",
  },
  {
    title: "Usuarios",
    class: "slidebar-nav-item",
    url: "/dashboard/usuarios",
    urlClass: "slidebar-nav-link",
    icon: AccountBox,
    iconClass: "slide-icon",
  },
  {
    title: "Productos",
    class: "slidebar-nav-item",
    url: "/dashboard/productos",
    urlClass: "slidebar-nav-link",
    icon: Storefront,
    iconClass: "slide-icon",
  },
  // {
  //   title: "Servicios",
  //   class: "slidebar-nav-item",
  //   url: "/dashboard/servicios",
  //   urlClass: "slidebar-nav-link",
  //   icon: Shop,
  //   iconClass: "slide-icon",
  // },
  {
    title: "Agenda",
    class: "slidebar-nav-item",
    url: "/dashboard/agenda",
    urlClass: "slidebar-nav-link",
    icon: EventAvailable,
    iconClass: "slide-icon",
  },
  // {
  //   title: "Calendario",
  //   class: "slidebar-nav-item",
  //   url: "/dashboard/calendario",
  //   urlClass: "slidebar-nav-link",
  //   icon: Today,
  //   iconClass: "slide-icon",
  // },
  {
    title: "Reportería",
    class: "slidebar-nav-item",
    url: "/dashboard/reporteria",
    urlClass: "slidebar-nav-link",
    icon: ListAlt,
    iconClass: "slide-icon",
  },
  {
    title: "Inventarios",
    class: "slidebar-nav-item",
    url: "/dashboard/inventario",
    urlClass: "slidebar-nav-link",
    icon: ViewList,
    iconClass: "slide-icon",
  },
  // {
  //   title: "Test",
  //   class: "slidebar-nav-item",
  //   url: "/dashboard/test",
  //   urlClass: "slidebar-nav-link",
  //   icon: Block,
  //   iconClass: "slide-icon",
  // },
];
